# Generated by Django 3.2.9 on 2022-07-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_write'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='write',
            name='description',
            field=models.TextField(default=1, max_length=4000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='write',
            name='title',
            field=models.CharField(default=2, max_length=225),
            preserve_default=False,
        ),
    ]
