# Generated by Django 3.2.9 on 2022-07-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_auto_20220716_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='write',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='display.write'),
        ),
    ]
